### ISSUE TITLE
Gerber-Lage Top Copper gegenüber den anderen Lagen verschoben

### ISSUE THREAD

**Issue by papamidas** [MakeMagazinDE/Smart-Dimmer#1]
Hi,
mein Gerber-Viewer zeigt mir, dass die obere Kupferlage in der Gerber-Datei
iot_dimmer_v02 - Top Copper.gbr
gegenüber den anderen Lagen vertikal um 3,8 mm nach unten verschoben ist.

**Comment by gdampf** [comment]
Ich habe  die Gerber-Dateien, so, wie sie sind an JLCPCB geschickt und inzwischen einwandfreie Platinen erhalten - nix ist verschoben.
Also entweder ist der Gerber-Viewer von papamidas Schrott, oder die Chinesen sind (trotz Corona) so nett und haben den Fehler korrigiert. Ich glaube aber eher an ersteres.

**Comment by papamidas** [comment]
Hallo gdampf, ich habe die Gerber-Dateien ebenfalls unverändert an JLCPCB geschickt und einwandfreie Platinen erhalten.
Als Gerber-Viewer hab ich den von KICAD 5.1.4 verwendet; der ist nach meiner Erfahrung eigentlich kein Schrott! Könnten also doch evtl. nette Chinesen im Spiel gewesen sein.
